### ISSUE TITLE
Will be supported Grails 3.x?

### ISSUE THREAD

**Issue by magx2** [TheConnMan/SlackLogger#1]
I'm just wondering if this plugin support Grails 3? I must say that I'm pretty interested in this feature.

**Comment by TheConnMan** [comment]
Yes, I can add Grails 3 support. I'm glad to see some interest in the plugin!

**Comment by magx2** [comment]
Slack is on hype so it's good to have Grails 3.x version :).

PS thank for your work with this plugin :)

**Comment by magx2** [comment]
Any update?

**Comment by TheConnMan** [comment]
Made it halfway through the upgrade over the weekend, will hopefully finish it this weekend.

**Comment by magx2** [comment]
Don't want to be nagger, but did you finished?

**Comment by TheConnMan** [comment]
No, but thanks for keeping me honest. I'll work on this now.
